### ISSUE TITLE
recordScreentime 参数无效

### ISSUE THREAD

**Issue by tzwhyqq** [xy-sea/web-see#29]
recordScreentime 设置了20秒，最后视频的长度还是10秒。这个需要其他什么配置吗

**Comment by xy-sea** [comment]
不需要其他配置 刚刚实测 recordScreentime: 20 是有效的

**Comment by tzwhyqq** [comment]
我拿demo 测试的。我设置了25。 然后第一次 js报错，出现时长是 33 秒，然后前面10秒是有内容的，后面的速度很快而且内容也一样。

**Comment by tzwhyqq** [comment]
好像是dist文件夹的问题，我升级到1.2.2 然后把demo 里面的 dist 文件删除后，再 npm run build  就好了。
