### ISSUE TITLE
npm切换国内源问题

### ISSUE THREAD

**Issue by dlpuzhangyue** [xy-sea/web-see#36]
首先： 大佬牛b！

问题：
1. 由于公司网络原因问题，需要切换npm源为国内
2. 切换后使用pnpm 安装@websee/core 版本为3.2.1,就很奇怪！去npm查看当前最新为3.0.0
3. 而@websee/performance 依赖@websee/core@3.0.0版本 导致无法进行安装

<img width="563" alt="image" src="https://user-images.githubusercontent.com/29819173/234521447-a8184c4e-8fb7-4e9a-98c3-611f671bcc3e.png">

这是为什么呢，小白期待您的回复

**Comment by dlpuzhangyue** [comment]
完美！

**Comment by xy-sea** [comment]
cnpm和npm不同步🤣
